language: bash

before_install:
    - sudo apt-get update
    
install:
    - sudo apt-get install libxml2-dev libxslt-dev python-dev
    - sudo apt-get install python-pip 
    - sudo pip install lxml

script:
    - python python/check-xml.py
    - python python/validate-xml.py
